### ISSUE TITLE
Bagel configuration syntax errors

### ISSUE THREAD

**Issue by ryjmacdonell** [nubakery/bagel#102]
We are trying to test bagel for use with our quantum nuclear dynamics script, and we've run into some errors in the installation. During configuration, the configure script fails with
```
...
checking dependency style of g++... gcc3
..openmpi requested..
../configure: line 5360: syntax error near unexpected token `noext'
../configure: line 5360: `AX_CXX_COMPILE_STDCXX_11(noext)'
```
If I remove the noext variable (which seems to be unset), the script then fails at:
```
...
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
../configure: line 16232: syntax error near unexpected token `1.53,'
../configure: line 16232: `AX_BOOST_BASE(1.53, , AC_MSG_ERROR("BOOST version >= 1.53.0 required."))'
```
i.e. the action-if-found keyword is blank.

We are configuring with `--disable-scalapack` and `--with-mpi=openmpi`.

**Comment by shiozaki** [comment]
Thanks for the message. I think your libtool, autoconf or automake is too
old. Please revert your change and try newer versions. Otherwise I'm not
sure it will work.

The second problem seems that you did not provide the right paths for BOOST.

Finally, openmpi is buggy and not recommended.

Please look for more information in the manual at http://nubakery.org

I don't think this is a bug, so will close this in a few days.
