### ISSUE TITLE
Possible to get MO coefficients from rel. SCF calculations in text format?

### ISSUE THREAD

**Issue by P9k** [nubakery/bagel#110]
I know that there is a feature to write the MO coefficients from DHF calculations into a binary file for restart and non-relativistic calculations can write into MOLDEN format. But is there somehow an option (similar to DIRAC's DFPCMO file) to get the converged MO coefficients printed in human-readable format?
Sorry if it is in the manual and I just wasn't able to find it.
Thanks a lot!

**Comment by shiozaki** [comment]
We don't have that option (because Molden does not support complex numbers), but it is easy to implement it. Can you give me a link or documentation for the spec of DIRAC's DFPCMO file?

**Comment by P9k** [comment]
Wow, that was fast! :+1:  Thank you very much for looking into this!

Find attached examples for HF and DHF calculations of Ne calculated with DIRAC-17 and the dyall.acv3z basis set.

The format itself is not really documented, but you can find some information about it here:http://www.diracprogram.org/doc/release-17/tutorials/restart/dfcoef_and_dfpcmo.html

[mo_coeff_ne.tar.gz](https://github.com/nubakery/bagel/files/1840445/mo_coeff_ne.tar.gz)

**Comment by shiozaki** [comment]
Thanks, I will ask Dirac developers about the format (it's not clear to me from the output).

**Comment by P9k** [comment]
That is awesome, thanks a lot!

**Comment by P9k** [comment]
I've just stumbled across this post from the DIRAC mailing list:

https://groups.google.com/forum/#!searchin/dirac-users/DFPCMO$20|sort:date/dirac-users/ygLopzge3Wk/CzfIHtuoAgAJ

**Comment by shiozaki** [comment]
Thanks. I also got a reply from Trond Saue - I will implement this some time next week.

**Comment by P9k** [comment]
Very cool! 💯

**Comment by P9k** [comment]
Hi there, 
Just checking if you've had time to look into this feature?

**Comment by shiozaki** [comment]
Sorry I haven't been able to do this yet.

**Comment by P9k** [comment]
No worries! Thank you for the quick reply!

**Comment by shiozaki** [comment]
Hi there, I just implemented this feature. The output format is complex numbers with the Kramers +-+-... format in the ascending order of the orbital energies. With Dirac HF, 
```
{ "bagel" : [ 

{
  "title" : "molecule",
  "basis" : "tzvpp",
  "df_basis" : "tzvpp-jkfit",
  "angstrom" : false,
  "geometry" : [ 
    { "atom" : "He",  "xyz" : [   -0.000000,     -0.000000,      0.0000]}
  ]
},
{
  "title" : "dhf",
  "dfpcmo" : true
}
]}
```
With Dirac CASSCF, one has to specify "canonical" as well; otherwise "dfpcmo" will be ignored. The orbital energies printed are semi-canonical orbital energies (the Fock operator is diagonalized within the closed, active, and virtual blocks).
```
{ "bagel" : [ 

{
  "title" : "molecule",
  "basis" : "tzvpp",
  "df_basis" : "tzvpp-jkfit",
  "angstrom" : false,
  "geometry" : [ 
    { "atom" : "He",  "xyz" : [   -0.000000,     -0.000000,      0.0000]}
  ]
},
{
  "title" : "zcasscf",
  "state"  : [1],
  "canonical" : true,
  "dfpcmo" : true,
  "nact"      : 2,
  "nclosed"   : 0 
}
]}
```

I think the code is correctly working, though I haven't tested carefully. If you find some weird behavior or should you have any suggestions, please let me know.

**Comment by shiozaki** [comment]
Note that I didn't use the quaternion format because (1) BAGEL does not use quaternions internally; (2) Dirac HF is not Kramers adapted (whereas Dirac CASSCF is Kramers adapted).

**Comment by P9k** [comment]
Thank you very much! I will test it a bit and report back if any problems arise.

**Comment by P9k** [comment]
Hi again,

I was able to run a test job and in principle everything works, I am only having some difficulties in reading the MO coefficients format from BAGEL.

[DFPCMO_BAGEL_HE_STO-3G.txt](https://github.com/nubakery/bagel/files/1874583/DFPCMO_BAGEL_HE_STO-3G.txt)

[DFPCMO_DIRAC_HE_STO-3G_SYM.txt](https://github.com/nubakery/bagel/files/1874584/DFPCMO_DIRAC_HE_STO-3G_SYM.txt)

[DFPCMO_DIRAC_HE_STO-3G_NOSYM.txt](https://github.com/nubakery/bagel/files/1874585/DFPCMO_DIRAC_HE_STO-3G_NOSYM.txt)

Both programs give the same orbital energies but I can't find the MO coefficients corresponding to each other. Is there something I am not seeing correctly?

Thanks again!

**Comment by shiozaki** [comment]
There is no correspondence. Please read the following carefully:

BAGEL prints as a large complex matrix, whereas DIRAC uses quaternion format. We do not use quaternion packing internally + BAGEL does not use Kramers symmetry in Dirac HF, so it's not possible for us to use the same format.

BAGEL's output format is 4x4 (rows are L+, L-, S+, S-; columns are MOs with Kramers +-+-... orders in the amending order of orbital energies). So in this example, the first four numbers correspond to the first MO; 5th-8th numbers correspond to the second MO, and these two are degenerate due to the Kramers symmetry (hence the same orbital energies).

The small components are spanned by RKB basis, and there seems a difference (by scalar... maybe by 2c?) in convention between BAGEL and DIRAC.

My suggestion would be to generate this file using BAGEL's Dirac CASSCF, which is Kramers adapted. You should then be able to transform this into quaternion format (the quaternion coefficients are complex in this case). You will then be able to see the correspondence between what BAGEL and DIRAC generate.
