### ISSUE TITLE
Error in dfpcmo when using openmpi

### ISSUE THREAD

**Issue by jesusG-V** [nubakery/bagel#115]
Dear BAGEL developers,

I found a problem when compiling with openmpi (I know it is not recommended) during the linking process:

dirac.cc:(.text+0x5372): undefined reference to `bagel::DFPCMO::DFPCMO(std::shared_ptr<bagel::ZMatrix const>, std::shared_ptr<bagel::Vector_<double> const>, double, int, int, int)'
dirac.cc:(.text+0x53a0): undefined reference to `bagel::DFPCMO::print() const'

Before this modification it was working smoothly

**Comment by shiozaki** [comment]
Thanks for reporting this - most likely this is to do with the ordering of the shared library, so needs some fix. Can you give me the configure options you used so that I can reproduce the problem? If you cannot figure it out, please send me the config.status file.

In the mean time, if you compile bagel with "--disable-shared --enable-static", you should be able to compile the program. If this does not work, please do "autoreconf" in the root directory and compile again...

**Comment by shiozaki** [comment]
Sounds good!
