### ISSUE TITLE
error with writing molden file

### ISSUE THREAD

**Issue by xubwa** [nubakery/bagel#122]
When I was trying to write the orbital information to the molden file for NpO2^2+ with the ano basis, there is this error " ERROR: EXCEPTION RAISED:  vector::_M_range_check: __n (which is 5) >= this->size() (which is 5) ". I think it is because in the moldenio class, the b2m_sph_ is constructed only up to g orbitals. Do you have any idea how to fix that?

**Comment by shiozaki** [comment]
I’ll take a look. I’m not sure if the Molden format standard specifies shell ordering beyond g shells, and that could have been the reason. If so, I’m not sure what to be done. If this is just lack of code, it’s easy to fix.

I’d suggest using smaller basis For visualization if possible.

**Comment by xubwa** [comment]
I just looked at the Molden format standard, it seems that the g shell is the last one. But if I simply want to make it to work with the h shell on a modified version that I am using, what value should I put on the const_scales for the h shell?

**Comment by shiozaki** [comment]
It's undefined. What specifically do you want to do with your code? If it is restart, use "save" instead. If you want to visualize it, then it depends on the own convention of the visualizer that you use (which I don't know).

In any case I'll take a look tonight.

On Jul 30, 2018, at 4:49 PM, Xubo Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


I just looked at the Molden format standard, it seems that the g shell is the last one. But if I simply want to make it to work with the h shell on a modified version that I am using, what value should I put on the const_scales for the h shell?

-

**Comment by xubwa** [comment]
Thanks for that.

**Comment by shiozaki** [comment]
But can you answer my question above?

On Jul 30, 2018, at 4:54 PM, Xubo Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for that.

-

**Comment by xubwa** [comment]
I want to visualize the orbital with Multiwfn.

**Comment by shiozaki** [comment]
Then please ask the developer of the Miltiwfn for their convention. If you have the reply, I can suggest something.

On Jul 30, 2018, at 5:00 PM, Xubo Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


I want to visualize the orbital with Multiwfn.

-

**Comment by xubwa** [comment]
The developer of the Multiwfn showed me his scheme of dealing with h shell. Is there any suggestion?
![image](https://user-images.githubusercontent.com/34044625/43473726-318b00a2-94ae-11e8-83ed-9fb44b180112.png)

**Comment by shiozaki** [comment]
Here I will explain to you how these factors in const_scale was calculated. I ask that you figure out the ordering etc by yourself.

The const_scale is a factor associated with each of the Cartesian components in the BAGEL convention. The BAGEL's cartesian components are ordered in the order of the compliments. For instance, for the D shells, the order is [xx, xy, yy, xz, yz, zz], because their compliments are [yyzz, xyzz, xxzz, xyyz, xxyz, xxyy] - the compliments are in the reverse dictionary order.

The factor in const_scale is to do with normalization of the each of the Cartesian components. Knowing
```
Integral[ exp(-x^2), x, -infty, infty ] = sqrt(pi)
Integral[ x^2 exp(-x^2), x, -infty, infty ] = 1/2 * sqrt(pi)
Integral[ x^4 exp(-x^2), x, -infty, infty ] = 3/4 * sqrt(pi)
```
you get that the norm of the first component (xx) is sqrt((sqrt(pi))^3 * 3/4). You get the norm of the second component (xy) is sqrt((sqrt(pi))^3 * 1/4). Therefore there is a factor of sqrt(3) in between. I forgot the details of the convention, but it should be straightforward. Note that this factor is used in the denominator (look at https://github.com/nubakery/bagel/blob/master/src/util/io/moldenout.cc).


That all said, I don't think it's a good idea to use cartesian basis. If you are only interested in visualizing spherical basis, then you should just have to be filling in b2m_sph, which has a simple pattern.

Hope this helps. These are trivial stuff - you should discuss your supervisor. I will close this case.
