### ISSUE TITLE
How to configure the memory per processor in BAGEL program

### ISSUE THREAD

**Issue by dpvalverde** [nubakery/bagel#146]
Hi everyone,

I would like to configure the memory used by each mpi processor. I know I can configure the number of processors. However, I did not find nothing about the memory. Is there a way to restrict the total memory used by the BAGEL program ?

Best Regards,
Danillo Valverde

**Comment by shiozaki** [comment]
Short answer is no. This is in part because BAGEL is designed for parallel computing environments, and the memory requirement almost linearly decreases with respect to the number of nodes you use.

That said, for CASSCF / CASPT2, often setting "davidson_subspace" to a small number (3 etc) helps reduce the memory requirement.
