### ISSUE TITLE
Problem with a frequency calculation

### ISSUE THREAD

**Issue by AlexPrihodko** [nubakery/bagel#148]
![image](https://user-images.githubusercontent.com/43905853/51434344-a794b880-1c6f-11e9-87cb-5e51a99b9b20.png)

Calculation failed with this error. How can I solve it?

**Comment by shiozaki** [comment]
There must be a log file produced by the queue system that should have more information. With this report, there is no way we can address your problem. Please narrow down your problem including runtime environment and make an failing input that runs in a few seconds if you want us to look at it (otherwise we cannot).
