### ISSUE TITLE
Relativistic NEVPT2

### ISSUE THREAD

**Issue by xubwa** [nubakery/bagel#201]
Hi bagel developers,
I read in your paper [Relativistic Internally Contracted Multireference Electron Correlation Methods](https://arxiv.org/pdf/1508.01461.pdf) that you guys have relativistic CASPT2, NEVPT2, MRCI implemented. While I can find both on manual and src the RelCASPT2 and RelMRCI, I couldn't find much information related to relativistic NEVPT2. Is this functionality hidden somewhere or it is not commited to this repo?
Best,
Xubo

**Comment by shiozaki** [comment]
After publication, I realized that relativistic NEVPT2 is not a great method. This is because sc-NEVPT2 is not invariant with respect to rotation within the active space, and because relativistic systems always have Kramers degeneracy which allows rotation of orbitals. In other words, the relativistic sc-NEVPT2 is not well defined. The code is implemented, the title should be "dnevpt2" (the code is in pt2/nevpt2, which is completely templated with respect to types).

**Comment by xubwa** [comment]
So the take home message would be, it is there, but we shouldn't use it, right?
Best,
Xubo

**Comment by shiozaki** [comment]
Yes. There is (at least, was) an emulated pc-NEVPT2 code. That thing works well (at least better than CASPT2) for ZFS for instance, see, 10.1021/acs.jctc.8b00910. Probably still can be run, in smith, method: "casa" and  block_diag_fock: true

**Comment by xubwa** [comment]
Thank you, that seems work, just a bit slow. I'll close this issue.
