### ISSUE TITLE
Using diffuse basis sets

### ISSUE THREAD

**Issue by papai-coder** [nubakery/bagel#205]
Dear developers,

Is there any possibility to use diffuse basis set, such as aug-cc-pVDZ in BAGEL? Although I can see that this basis set is available in the basis set library, I am unsure which density fitting basis set to combine with. I have implemented the universal def2/JK and aug-cc-pvDZ-RIfit basis set, but when combined with aug-cc-pVDZ, I get VERY strange results. When doing a SA-CASSCF calculation for 5 singlet states, 2 out of the 5 states converge to triplets during the CI iterations. I am not sure whether this is connected to the density fitting basis set, but I didn't get it for other molecules when using cc-pVDZ/cc-pVDZ-jkfit (for the target molecule a diffuse basis set is mandatory as I am dealing with Rydberg states).

Thank you in advance for your help. 

Matyas Papai

**Comment by shiozaki** [comment]
In most cases, aug-cc-pVDZ / cc-pVDZ-JKFIT is sufficient (see for example, http://www.psicode.org/psi4manual/master/basissets_byfamily.html where cc-pVDZ-JKFIT and aug-cc-pVDZ-JKFIT seem identical). If you feel that you need more diffuse fitting basis set, you could add a diffuse function in the fitting basis. For example, if you have an exponent for a S shell
```
[10.0, 2.2, 1.0, 0.5]
```
then take a ratio of the two most diffuse functions (in this case 2) and extrapolate it
```
[10.0, 2.2, 1.0, 0.5, 0.25]
```

But I'd speculate that the cause of your problem is actually the choice of active spaces (and initial orbitals). There is "active" keyword that you could play with. Unfortunately I will not be able to help on specific inputs.

**Comment by papai-coder** [comment]
Thanks!!

**Comment by shiozaki** [comment]
oh by the way, forgot to mention. RIFIT is not for CASSCF. It does not have core functions (designed for the correlation part of the MP2 calculation - read the original papers by (probably) Weigend) Cheers
