### ISSUE TITLE
ZHarrison tests do not pass

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#47]
TEST_RELFCI does not pass. For the time being they are commented out in test_main.cc
```
Entering test case "ZHARRISON"
Assertion failed: ((*this - *(this->transpose_conjg())).norm()/size() < 1e-10), function diagonalize, file ../../../src/math/zmatrix.cc, line 95.
```

**Comment by shiozaki** [comment]
Ryan, can you take care of it and include the tests before we break the code?

**Comment by RDReynolds** [comment]
I think restricting the Davidson subspace is sufficient for our test cases, although numerical stability could still be an issue for harder problems.  I've also set certain symmetry checks to print a warning rather than shutting down.  

I have reactivated the various test cases, with the exception of o2_svp_triplet_breit.json, which currently hits the max number of microiterations without convergence.  I suspect that this problem is unrelated.

**Comment by shiozaki** [comment]
Thanks! I will compile and run the test cases - if all pass, I will close the issue.
