### ISSUE TITLE
basis set projection in relativistic code

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#62]
When geometry is changed, one has to do basis set projection that is a bit different from that used when changing basis set at the same geometry. See reference.cc.

**Comment by shiozaki** [comment]
@RDReynolds Do you know what has been done for this? Or is it now OK?

**Comment by shiozaki** [comment]
@RDReynolds ?

**Comment by RDReynolds** [comment]
I have updated the relativistic coefficient projection.  It works now with small geometry changes for both relativistic and non-relativistic Hartree--Fock and CASSCF.  

Change of basis set also works for (rel + nonrel) Hartree--Fock, as well as nonrel CASSCF.  With relativistic CASSCF and a change in basis set, the program crashes, seemingly due to a mismatch in the size of some matrices.

**Comment by RDReynolds** [comment]
The problem with change in basis set for rel. CASSCF has been fixed as well now, using SVD as is done in the nonrel case to generate orthogonal virtual orbitals.  We then have to Kramers-adapt the orbitals, which currently uses a Fock matrix and could potentially change the closed + active spaces more than I would like...  but it works and produces a reasonable guess.

**Comment by shiozaki** [comment]
@RDReynolds should I close?

**Comment by RDReynolds** [comment]
Yes, this issue can be closed.
