### ISSUE TITLE
Cannot compile in Ubuntu 14.04

### ISSUE THREAD

**Issue by Jellby** [nubakery/bagel#63]
I'm trying to compile Bagel in Ubuntu 14.04, and eventually it fails with:

    make[3]: Entering directory `/scr/ignacio/bagelobj/src'
    /bin/bash ../libtool  --tag=CXX   --mode=link g++ -I/home/ignacio/Programs/bagel -g -O2 -std=c++11   -o BAGEL main.o libbagel.la opt/libbagel_opt.la multi/zcasscf/libbagel_zcasscf.la ci/zfci/libbagel_zfci.la ci/fci/libbagel_fci.la ci/ras/libbagel_ras.la scf/libbagel_scf.la multi/casscf/libbagel_casscf.la pt2/libbagel_pt2.la grad/libbagel_grad.la wfn/libbagel_wfn.la df/libbagel_df.la smith/libbagel_smith.la prop/libbagel_prop.la asd/libbagel_asd.la asd/dmrg/libbagel_asd_dmrg.la asd/orbital/libbagel_asd_orbital.la asd/dimer/libbagel_dimer.la asd/multisite/libbagel_multisite.la ci/ciutil/libbagel_ciutil.la mat1e/libbagel_mat1e.la util/io/libbagel_io.la molecule/libbagel_molecule.la integral/libbagel_integral.la alglib/libbagel_alglib.la -lboost_unit_test_framework -lboost_regex -lboost_serialization 
    libtool: link: g++ -I/home/ignacio/Programs/bagel -g -O2 -std=c++11 -o .libs/BAGEL main.o  ./.libs/libbagel.so opt/.libs/libbagel_opt.so multi/zcasscf/.libs/libbagel_zcasscf.so ci/zfci/.libs/libbagel_zfci.so ci/fci/.libs/libbagel_fci.so ci/ras/.libs/libbagel_ras.so scf/.libs/libbagel_scf.so multi/casscf/.libs/libbagel_casscf.so pt2/.libs/libbagel_pt2.so grad/.libs/libbagel_grad.so wfn/.libs/libbagel_wfn.so df/.libs/libbagel_df.so smith/.libs/libbagel_smith.so prop/.libs/libbagel_prop.so asd/.libs/libbagel_asd.so asd/dmrg/.libs/libbagel_asd_dmrg.so asd/orbital/.libs/libbagel_asd_orbital.so asd/dimer/.libs/libbagel_dimer.so asd/multisite/.libs/libbagel_multisite.so ci/ciutil/.libs/libbagel_ciutil.so mat1e/.libs/libbagel_mat1e.so util/io/.libs/libbagel_io.so molecule/.libs/libbagel_molecule.so integral/.libs/libbagel_integral.so alglib/.libs/libbagel_alglib.so -lboost_unit_test_framework -lboost_regex -lboost_serialization -Wl,-rpath -Wl,/usr/local/bagel/lib
    /usr/bin/ld: main.o: undefined reference to symbol '_ZNK5bagel7Process8cout_offEv'
    //home/ignacio/Programs/bagel/obj/src/util/parallel/.libs/libbagel_parallel.so.0: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    make[3]: *** [BAGEL] Error 1
    make[3]: Leaving directory `/scr/ignacio/bagelobj/src'
    make[2]: *** [all-recursive] Error 1
    make[2]: Leaving directory `/scr/ignacio/bagelobj/src'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/scr/ignacio/bagelobj'
    make: *** [all] Error 2

I've read there may be problems with different libboost versions, mine is 1.55. I've tried configuring with a plain ``configure`` and with ``configure 'LDFLAGS=-L/usr/lib -lblas -llapack'``

**Comment by shiozaki** [comment]
Thanks much for this report. This is, however, likely not a bagel problem, so I will close this issue and let us discuss via emails.

(1) does this file exist? /home/ignacio/Programs/bagel/obj/src/util/parallel/.libs/libbagel_parallel.so.0 ? Can you read the symbol (open with vi and grep "cout_off")? What about dependency (can be checked with "ldd")?

(2) Can you please instead send me an email with details (config.status, git diff, gcc --version, automake autoconf autoheader version etc)? Your like line does not quite look like what you described above (maybe that's ubuntu thing). Also it would be useful if you "make distclean" and then "make" while recording all the output from compilation, and send it to me. Furthermore, It'd be helpful if you let us know whether you tried this on different hardware, software etc?

I have no Ubuntu 14.04 (and won't test this code for all the hardware in any case), so to some extent I am relying on the users' ability to troubleshoot - with only three people in my group, I am afraid we are severely limited by human resources.

**Comment by mbanck** [comment]
FWIW, I've been seeing this link error on Debian/Ubuntu as well. I've added util/parallel/libbagel_parallel.la (and for good measure util/math/libbagel_math.la util/input/libbagel_input.la and util/libbagel_util.la as well) to INTLIBS to make it link correctly and I've wondering how this is supposed to work without those in INTLIBS. This is the patch I'm using, it might help the original reporter as well:

http://anonscm.debian.org/viewvc/debichem/unstable/bagel/debian/patches/fix_linking_error.patch?view=markup

On the other hand, I'd be happy to learn how this can be avoided.

**Comment by shiozaki** [comment]
It should in principle work (and in practice it does in most systems) because some other libbagel**.so knows libbagel_parallel.so (i.e., if you ldd, you will see them; so all the symbols are visible at run time). I have never heard of this error with quite a few users, but maybe they are just changing these things by themselves.

Let me know what we have in bagel is not standard compliant - then I will take care of it. If not I will leave it as it is. The reason why I removed these things from the Makefile.am was to enforce the library hierarchy, which is not perfect in bagel.

As a side note, we are not writing bagel so that it runs on every machine, though we do hope that it is useful for some people. We (as a group of tenure tracking assist professor consisting of 3 people) just cannot afford it. Cheers.

**Comment by mbanck** [comment]
Thanks for the pointer, I see the indirect linking now. I believe what happens is that Debian/Ubuntu either use a different linker (Gold maybe) to most people, or they modified its behavior to not allow for indirect linking. The main reason for this behavior change however appears to be for library hierarchies beyond project boundaries (so that the directly linked library cannot change its linking and suddenly drop the indirectly linked one), which is not the bagel case. Fedora seem to have at least proposed something similar as well: https://fedoraproject.org/wiki/UnderstandingDSOLinkChange

About standard compliance I don't know, but I guess the current linking probably is standard compliant. So it makes sense to just add those libtool objects explicitly if the system requires it.

**Comment by shiozaki** [comment]
Thanks - I also added a note on github Wiki that we recommend GNU Binutils. Hopefully it would do for the time being. Cheers.

**Comment by Jellby** [comment]
Thanks for the comments. As far as I can see, Ubuntu is using GNU ld, but defaults to no indirect linking (see https://wiki.ubuntu.com/NattyNarwhal/ToolchainTransition#Indirect_Linking_for_Shared_Libraries). I could get bagel to compile (and link) with:

    configure 'LDFLAGS=-L/usr/lib -lblas -llapack' 'CXXFLAGS=-Wl,--copy-dt-needed-entries -Wl,--no-as-needed'

I don't know how this relates to standard compliance, but note that GNU ld's manual (https://sourceware.org/binutils/docs/ld/Options.html#Options) says that the default is ``--no-copy-dt-needed-entries`` too.

**Comment by shiozaki** [comment]
intersting - I am using GNU Binutils on several architectures (mac os, centos (redhat), even on computers from 90s) and all seem to work without any flags. I'll leave it as it is now.
