### ISSUE TITLE
Restart capability

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#9]
Have not designed this at all. Needs to be implemented.

**Comment by RDReynolds** [comment]
I have added restart capability to relativistic CASPT2 (not yet on Master branch).  

I initially tried to keep the same interface, but this was impractical because bagel::SMITH::SpinFreeMethod is not derived from bagel::Method.  Instead, we just serialize SMITH_Info and the MultiTensor containing T-amplitudes; everything else is recomputed.  A sample input for a restarted job follows.  The last input parameter ("state_begin") is only needed for multi-state calculations where T-amplitudes for some states have already converged.  

{
  "title" : "relsmith",
  "method" : "continue",
  "archive_location" : "/some/directory",
  "restart_iter" : "6",
  "state_begin" : "2" 
}

**Comment by shiozaki** [comment]
I think we are sort of OK in this front. Closing for now.
